sudo: false
language: java
jdk:
- oraclejdk8
install: gradle assemble
script: gradle build --continue
before_install:
- pwd
- openssl aes-256-cbc -K $encrypted_b07074037f75_key -iv $encrypted_b07074037f75_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 101.132.155.26\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- pwd
- tar -jcf test.tar.bz2 *
- scp test.tar.bz2 root@101.132.155.26:~/
